### ISSUE TITLE
filling does not work

### ISSUE THREAD

**Issue by christf** [arcnmx/luakit-pass#1] opened 2018-03-29 22:23 UTC
Very cool stuff!

pshow works well but :pass does not fill a field on wiki.ffm.freifunk.net for example.
Also, how do I fill in user names?

... maybe this should also read: user-documentation still has some potential

**Comment by arcnmx** [comment] 2018-03-29 22:41
Duplicate of #2

**Closed by arcnmx** 2018-03-29 22:41 UTC
